### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by gggggk0117** [WujiangXu/NMCDR#1]
您好！代码中数据处理部分似乎有些不完善，或许您能写一份如何运行的提示吗？

**Comment by WujiangXu** [comment]
请问具体是哪里遇到问题呢，最近我们也在使用这份代码。

之后，我们也会完善我们的代码 包括注释和使用方式。

**Comment by gggggk0117** [comment]
感谢回复，代码中部分数据文件我未能跑出来，也尝试过使用您注释过的代码。
期待您后续的使用注释。

**Comment by WujiangXu** [comment]
> 感谢回复，代码中部分数据文件我未能跑出来，也尝试过使用您注释过的代码。 期待您后续的使用注释。

最近测试并更新了代码，可以重新尝试一下。
